updated sway added notifications, udated keybinds, added window rules

diff --git a/.local/bin/gamemode b/.local/bin/gamemode
--- a/.local/bin/gamemode
+++ b/.local/bin/gamemode
@@ -1,5 +1,8 @@
 #!/usr/bin/env sh
 
+set -u          #Detect undefined variable
+set -o pipefail #Return return code in pipeline fails
+
 HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
 if [ "$HYPRGAMEMODE" = 1 ]; then
     hyprctl --batch "\
